# Generated by Django 5.1 on 2024-09-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='edd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
