# Generated by Django 5.1 on 2024-09-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shipment_dimensions_shipment_edd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
